version: "3"

# Infrastructure required for the Data Project 4

services:
  
  maas:
    container_name: maas
    
    build:
      context: ./team_deploy/app
      dockerfile: Dockerfile

    volumes:
      - ./bucket_images:/code/images

    ports:
      - "5000:5000"


  ingestion:
    container_name: ingestion

    build:
      context: ./team_arch
      dockerfile: Dockerfile

    volumes:
      - ./bucket_images:/ingestion/images
