version: "3"

services:
  maas:
    container_name: maas
    
    build:
      context: ./app
      dockerfile: Dockerfile

    volumes:
      - ./bucket_images/:/code/images

    ports:
      - "5000:5000"